---
abstract: 'Modules that DBR likes to use.'
author:
  - 'Daniel B <dbrx@dbrx.crux.uberspace.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-DBR
requires:
  App::Ack: 0
  Bread::Board: 0
  Bread::Board::Declare: 0
  DBIx::Class: 0
  Data::Visitor: 0
  DateTime: 0
  Devel::NYTProf: 0
  Dist::Zilla: 0
  JSON: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  Path::Class: 0
  Task::Kensho: 0
  Task::Moose: 0
  WWW::Mechanize: 0
  Web::Scraper: 0
  YAML: 0
version: 0.001
x_authority: cpan:DBR
